#!/usr/bin/env bash

currDirectory=$(pwd)

echo -e "\nAccessing sysfs info:"
cd /sys/devices/system/cpu/cpu0/cpufreq/
echo -e "\nCPU max frequency:"
cat cpuinfo_max_freq

echo -e "\nCPU min frequency:"
cat cpuinfo_min_freq

cd $currDirectory
g++ -Werror lab5_pt1.cpp 
wait
echo -e "\nRunning workload"
./a.out
wait

echo "Running userspace CPU Governor"
g++ -Werror "$currDirectory"/lab5_pt2.cpp
wait
sudo ./a.out


